version: "3.8"

services:
    backend:
        container_name: cpj-backend
        image: python:3.9
        restart: unless-stopped
        command: sh -c "cd /app && pip install -r requirements.txt && pip install uvicorn && uvicorn main:app --host 0.0.0.0 --port 8000"
        ports:
            - 8000:8000
        volumes:
            - .:/app      
        env_file: 
            - .env
        environment:
            - TZ=Asia/Taipei